---
- name: Install Node Exporter
  hosts: all
  become: yes

  tasks:
    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        url:https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.darwin-amd64.tar.gz
        dest: /tmp/node_exporter-1.5.0.darwin-amd64.tar.gz

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt
        remote_src: yes
        copy: no
        creates: /opt/node_exporter-{{ node_exporter_version }}

    - name: Create systemd service for Node Exporter
      systemd:
        name: node_exporter
        daemon_reload: yes
        enabled: yes
        state: started
        user: root
        unit_content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          ExecStart=/opt/node_exporter-{{ node_exporter_version }}/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target
