- name: Add Loki repository
  apt_repository:
   repo: 'deb https://packages.grafana.com/loki/deb stable main'
   state: absent
   update_cache: false

- name: Install Loki
  apt:
    name: loki
    state: present

- name: Configure Loki
  copy:
     src: loki-config.yaml
     dest: /etc/
  notify: restart loki
- name: service Loki
  copy:
    src: loki.service
    dest: /etc/systemd/system/
  notify: restart loki
    
