- name: Deploy Docker container
  hosts: docker
  vars:
    image_name: vinodpatlolla/docker
    image_tag: latest
    container_name: docker_app
    port_mappings:
      - "9000:8080"
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ vinodpatlolla/docker }}:{{ latest }}"
        source: pull

    - name: Start Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ vinodpatlolla/docker }}:{{ latest }}"
        state: started
        published_ports: "{{ 9000 }}"
