---
- name: Install Docker, Prometheus, Grafana, and Node Exporter
  hosts: all
  become: true
  vars:
    prometheus_version: "2.32.1"
    node_exporter_version: "1.2.2"
    grafana_version: "8.3.0"
    grafana_admin_user: "admin"
    grafana_admin_password: "admin"
  tasks:
    # Install necessary dependencies
    - name: Install aptitude package manager
      apt:
        name: aptitude
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary dependencies
      apt:
        name:
          - curl
          - wget
          - gnupg2
          - software-properties-common
        state: present

    # Install Docker
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce docker-ce-cli containerd.io
        state: present

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Install Prometheus
    - name: Create Prometheus Docker container
      docker_container:
        name: prometheus
        image: prom/prometheus:{{ prometheus_version }}
        ports:
          - "9090:9090"
        volumes:
          - "/home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml"
        restart_policy: always

    # Install Grafana
    - name: Create Grafana Docker container
      docker_container:
        name: grafana
        image: grafana/grafana:{{ grafana_version }}
        ports:
          - "3000:3000"
        environment:
          GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
          GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
        restart_policy: always

    # Install Node Exporter
    - name: Create Node Exporter Docker container
      docker_container:
        name: node-exporter
        image: prom/node-exporter:{{ node_exporter_version }}
        ports:
          - "9100:9100"
        restart_policy: always
