---
  #prometheus
- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restart
  listen: event_restart_prometheus

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload